# Generated by Django 6.0.2 on 2026-03-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrientationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_filiere', models.CharField(max_length=64, verbose_name='Code Filière')),
                ('universite', models.CharField(max_length=255, verbose_name='Université')),
                ('etablissement', models.CharField(max_length=255, verbose_name='Établissement')),
                ('filiere', models.CharField(max_length=255, verbose_name='Filière')),
                ('section_bac', models.CharField(max_length=10, verbose_name='Section Bac (code)')),
                ('section_bac_nom', models.CharField(max_length=255, verbose_name='Section Bac (nom)')),
                ('score_2022', models.FloatField(blank=True, null=True, verbose_name='Score 2022')),
                ('score_2023', models.FloatField(blank=True, null=True, verbose_name='Score 2023')),
                ('score_2024', models.FloatField(blank=True, null=True, verbose_name='Score 2024')),
                ('score_2025', models.FloatField(blank=True, null=True, verbose_name='Score 2025')),
            ],
            options={
                'verbose_name': "Dossier d'orientation",
                'verbose_name_plural': "Dossiers d'orientation",
                'ordering': ['universite', 'etablissement', 'filiere'],
                'unique_together': {('code_filiere', 'section_bac')},
            },
        ),
    ]
